// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities;

public partial class Dress
{
    public int Id { get; set; }

    public int ModelId { get; set; }

    public string Size { get; set; }

    public int Price { get; set; }

    public string Note { get; set; }

    public bool IsActive { get; set; }

    public virtual Model Model { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();
}