// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities;

public partial class Model
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string ImgUrl { get; set; }

    public int BasePrice { get; set; }

    public string Color { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<Dress> Dresses { get; set; } = new List<Dress>();

    public virtual ICollection<Category> Categories { get; set; } = new List<Category>();
}