// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities;

public partial class OrderItem
{
    public int Id { get; set; }

    public int DressId { get; set; }

    public int OrderId { get; set; }

    public virtual Dress Dress { get; set; }

    public virtual Order Order { get; set; }
}